services:
  # ----------------------------------------
  # Service 1: The Node.js Backend
  # ----------------------------------------
  - type: web
    name: medicine-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production

      # ---------------------------------------------------------
      # SECURE SETUP: 'sync: false' means you enter the password
      # on the Render Website, not in this file.
      # ---------------------------------------------------------
      - key: MONGO_URI
        sync: false
      
      - key: JWT_SECRET
        sync: false
      
      - key: ML_SERVICE_URL
        fromService:
          type: web
          name: medicine-ml-service
          property: url

  # ----------------------------------------
  # Service 2: The Python ML Service
  # ----------------------------------------
  - type: web
    name: medicine-ml-service
    env: python
    rootDir: ml-service
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free